name: Continuous Integration

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
            ~/.kebs-intellijPluginIC/
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}

      - name: Run tests
        run: sbt test
        shell: bash
  verify:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
            ~/.kebs-intellijPluginIC/
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}

      - name: Build the plugin
        run: sbt test packageArtifact
        shell: bash

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
        with:
          plugin-location: 'target/plugin/kebs-intellij/lib/kebs-intellij.jar'
          ide-versions: |
            ideaIC:2020.3.4
            ideaIU:2020.3.4
            ideaIC:2021.1.3
            ideaIU:2021.1.3
            ideaIC:LATEST-EAP-SNAPSHOT
            ideaIU:LATEST-EAP-SNAPSHOT
          failure-levels: |
            COMPATIBILITY_PROBLEMS
            INVALID_PLUGIN
