name: Publish kebs-intellij

on: release

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IJ_PLUGIN_REPO_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"

      - name: Publish plugin
        run: sbt clean test publishPlugin
