name: Publish to JetBrains Marketplace

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IJ_PLUGIN_REPO_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: "openjdk@1.17.0"

      - name: Package plugin
        # For some reason packageArtifact needs to be invoked second time
        # for patching plugin.xml in patchPluginXML task
        run: sbt clean test packageArtifact && sbt packageArtifact

      - name: Publish plugin
        run: sbt publishPlugin
